### ISSUE TITLE
Fix for Windows user

### ISSUE THREAD

**Issue by enzodev** [drush-ops/drush-launcher#59] opened 2018-06-06 11:39 UTC
drush updatedb doesn't work with windows, you get this error:

'C:/.../AppData/Roaming/Composer/vendor/drush/drush-launcher/bin/drush' is not
recognized as an internal or external command,
operable program or batch file.
 [error]  The command could not be executed successfully (returned: 'C:/.../Roaming/Composer/vendor/drush/drush-launcher/bin/drush' is not recognized as an internal or external command,
operable program or batch file.
, code: 1)

To fix it, you have to create a drush.bat file in ...\AppData\Roaming\Composer\vendor\drush\drush-launcher\bin

with these lines:

@echo off
php %~dp0\drush.php %*

In the main page the doc is outdated or wrong. You wrote user must look for drush.phar but there is no drush.phar installed. Also file content is outdated, you have to refer to drush.php and not drush.phar

**Comment by weitzman** [comment] 2018-06-06 11:41
Dupe of https://github.com/drush-ops/drush-launcher/pull/55 which was recently merged.

Also, we recommend installing the launcher via Phar, not composer.

**Closed by weitzman** 2018-06-06 11:41 UTC
